server {
    listen 80;

    location /api/reports/ {
        proxy_pass http://report-service:4000/reports/;
    }
    location /api/ {
        proxy_pass http://catalog-apix:3000/;
    }
    location = /admin {
        return 301 /admin/;
    }
    location /admin/ {
        proxy_pass http://admin-panel:8080/;
    }
    location / {
        proxy_pass http://frontend:8080;
    }
}
